work/claim/urls.py
from django.urls import path

from . import views

app_name = 'claim'

urlpatterns = [
    path('all/', views.claim_all, name='claim_all'),
    # path('detail/<int:claim_id>/', name='claim_detail'),
    path('create/', views.claim_create, name='claim_create'),
    path('update/<claim_id>/edit', views.claim_edit, name='claim_update')
]

work/console_repair/urls.py
from django.urls import path

from . import views

app_name = 'console_repair'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.console_repair_create, name='console_create'),
    path('console_repair/<int:repair_id>/',
         views.console_repair_detail, name='console_detail'),
    path('console_repair_all/', views.console_repair_all, name='console_all')
]

work/work/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',
         include(
             'console_repair.urls',
             namespace='console_repair')
         ),
    path('claim/',
         include
         ('claim.urls',
          namespace='claim')),
    path('admin/', admin.site.urls),
]

work/claim/models.py
from django.db import models


class ChoicesTypeOfStatus(models.TextChoices):
    IN_WORK_OFFICE = 'IWO', 'В работе(ОФИС)'
    IN_WORK_VALERA = 'IWV', 'В работе(ВАЛЕРА)'
    COMPLETED_OFFICE = 'CO', 'Выполнена(ОФИС)'
    COMPLETED_VALERA = 'CV', 'Выполнена(ВАЛЕРА)'
    CANSEL = 'C', 'ОТМЕНА'


class ChoicesTypeOfReason(models.TextChoices):
    OPTIC_FAIL = 'OF', 'OF'
    NOT_ENOUGH_SIGNAL = 'NES', 'Не хватает сигнала'
    OTHER = 'O', 'Другое'


class Claim(models.Model):
    order_outfit = models.CharField('ЗАКАЗ-НАРЯД', max_length=50, blank=True, )
    customer = models.CharField('ЗАКАЗЧИК', max_length=50)
    date_of_the_application = models.DateField('ДАТА ОБРАЩЕНИЯ', auto_now_add=True)
    number_of_contract = models.CharField("НОМЕР ДОГОВОРА", max_length=10)
    reason = models.CharField('ПРИЧИНА', choices=ChoicesTypeOfReason.choices, max_length=50)
    telephone_number = models.CharField('ТЕЛЕФОН', max_length=50)
    town = models.CharField('ПОСЕЛОК', max_length=50)
    street = models.CharField('УЛИЦА', max_length=50)
    house = models.CharField('ДОМ', max_length=50)
    comment_from_subscriber = models.TextField('КОММЕНТАРИЙ ОТ АБОНЕНТА', max_length=150, blank=True)
    status = models.CharField('СТАТУС', choices=ChoicesTypeOfStatus.choices, max_length=4, blank=True, null=True)
    repair_date = models.DateField('ДАТА РЕМОНТА', blank=True, null=True)
    comment_from_worker = models.TextField('КОММЕНТАРИЙ ОТ МОНТАЖНИКОВ', max_length=150, blank=True)
    sum = models.IntegerField("СУММА", blank=True, null=True)

    class Meta:
        ordering = ("-date_of_the_application",)
        verbose_name = "Заявки"
        verbose_name_plural = "Заявки"

        constraints = (
            models.CheckConstraint(
                name='valid_status_state_choice',
                check=models.Q(status__in=ChoicesTypeOfStatus.values)
            ),
            models.CheckConstraint(
                name='valid_reason_state_choices',
                check=models.Q(reason__in=ChoicesTypeOfReason.values)
            )
        )

    def get_status(self):
        return ChoicesTypeOfStatus(self.status)

    def get_reason(self):
        return ChoicesTypeOfReason(self.reason)

work/claim/forms.py
from django.forms import ModelForm
from django import forms

from .models import Claim


class ClaimForm(ModelForm):
    class Meta:
        model = Claim
        fields = '__all__'
        widgets = {
            'repair_date': forms.DateInput(attrs={'type': 'date'})
        }

work/claim/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .forms import ClaimForm
from .models import Claim


def claim_all(request):
    claim = Claim.objects.all()
    context = {
        'claims': claim,
    }
    return render(request, 'claim/claim_all.html', context)


def claim_detail(request, claim_id):
    claim = get_object_or_404(Claim, id=claim_id)
    context = {
        'claim': claim,
    }
    return render(
        request,
        'claim/claim_detail.html',
        context)


def claim_create(request):
    form = ClaimForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('claim:claim_all')

    context = {
        'form': form,
    }
    return render(request, 'claim/claim_form.html', context)


def claim_edit(request, claim_id):
    claim = get_object_or_404(Claim, id=claim_id)
    form = ClaimForm(request.POST or None,
                     instance=claim)

    if form.is_valid():
        form.save()
        return redirect("claim:claim_all")

    form = ClaimForm(instance=claim)

    context = {"form": form,
               "claim": claim,
               }
    return render(request, "claim/claim_update.html", context)

work/templates/claim/claim_all.html
<!DOCTYPE HTML>
{% load static %}
<html>
 <head>
  <meta charset="utf-8">
  <title>ЗАКАЗ НАРЯД</title>
    <style type="text/css">

    .oswmenu {
        font-size: 12pt;
        padding: 10px; /* Поля вокруг текста */
        opacity: .9;
        z-index: 5;
	font-family: 'Tahoma', sans-serif;
	color: #FFFFFF;
	background-color:#3d85c6;
    }

    .osw {
        font-size: 12pt;
        padding: 10px; /* Поля вокруг текста */
        opacity: .9;
        z-index: 5;
        font-family: 'Oswald', sans-serif;
    }



   TABLE {
	border-collapse: collapse;
	padding: 0px;

   }

    TD,TH  {
	border: 1px dashed black;
	padding: 5px;
	vertical-align: middle;
    }

    .TDS  {
	border: 0px;
	padding: 5px;
	vertical-align: middle;
    }



</style>
    <style type="text/css" media="print">
    @page {
        size: auto;   /* auto is the initial value */
        margin: 20;  /* this affects the margin in the printer settings */
    }
</style>

</head>
 <body>









    <table width="100%" >

	<tr ><td colspan=6 align=left class="TDS"><a class="brand" href="{% url 'console_repair:index' %}" title="КАТ-ТЕЛЕКОМ" aria-label="КАТ-ТЕЛЕКОМ"><img src="{% static 'img/logo_kat.png' %}" alt="" width="100"></a></td><td colspan=6 align=right class="TDS">Пользователь: {{ user.username }}</td><tr>

	<tr class="oswmenu" height="40" align="center">
	    <td><b>№</b></td>
	    <td><b>ДАТА ПОСТУПЛЕНИЯ</b></td>
		<td><b>ЗАКАЗ НАРЯД</b></td>
	    <td><b>ДОГОВОР №</b></td>
	    <td><b>ПРИЧИНА</b></td>
	    <td><b>К.ТЕЛЕФОН</b></td>
	    <td><b>ПОСЕЛОК</b></td>
	    <td><b>КОМЕНТАРИЙ ОТ АБОНЕНТА</b></td>
	    <td><b>СТАТУС</b></td>
	    <td><b>ДАТА РЕМОНТА</b></td>
	    <td><b>КОМЕНТАРИЙ ОТ МОНТАЖНИКОВ</b></td>
	    <td><b>ОЖИДАНИЕ</b></td>
	    <td><b>РЕДАКТИРОВАТЬ</b></td>
	</tr>

{% for claim in claims %}
	<tr class="osw" align="center">
	    <td>{{ claim.id }}</td>
	    <td>{{ claim.date_of_the_application }}</td>
		<td>{{ claim.order_outfit }}</td>
	    <td>{{ claim.number_of_contract }}</td>
	    <td>{{ claim.get_reason.label }}</td>
	    <td>{{ claim.telephone_number }}</td>
	    <td>{{ claim.town }}</td>
	    <td>{{ claim.comment_from_subscriber }}</td>
		<td>{% if claim.status %}{{ claim.get_status.label }}{% else %}{% endif %}</td>
	    <td>{{ claim.repair_date }}</td>
	    <td>{{ claim.comment_from_worker}}</td>
	    <td>{{ claim.repair_date }} - {{ claim.date_of_the_application }}</td>
	    <td><a href="{% url 'claim:claim_update' claim.id %}"><img src="{% static 'img/edit.png' %}" alt="" width="25"></a></td>
	</tr>
		{% endfor %}



    </table>






 </body>
</html>

work/templates/claim/claim_detail.html
<!DOCTYPE HTML>
{% load static %}
<html>
 <head>
  <meta charset="utf-8">
  <title>ЗАКАЗ НАРЯД</title>
    <style type="text/css">

    .oswmenu {
        font-size: 12pt;
        padding: 10px; /* Поля вокруг текста */
        opacity: .9;
        z-index: 5;
	font-family: 'Tahoma', sans-serif;
	color: #FFFFFF;
	background-color:#3d85c6;
    }

    .osw {
        font-size: 12pt;
        padding: 10px; /* Поля вокруг текста */
        opacity: .9;
        z-index: 5;
        font-family: 'Oswald', sans-serif;
    }



   TABLE {
	border-collapse: collapse;
	padding: 0px;

   }

    TD,TH  {
	border: 1px dashed black;
	padding: 5px;
	vertical-align: middle;
    }

    .TDS  {
	border: 0px;
	padding: 5px;
	vertical-align: middle;
    }



</style>
    <style type="text/css" media="print">
    @page {
        size: auto;   /* auto is the initial value */
        margin: 20;  /* this affects the margin in the printer settings */
    }
</style>

</head>
 <body>


    <table width="100%" >

	<tr ><td colspan=6 align=left class="TDS"><a class="brand" href="{% url 'console_repair:index' %}" title="КАТ-ТЕЛЕКОМ" aria-label="КАТ-ТЕЛЕКОМ"><img src="{% static 'img/logo_kat.png' %}" alt="" width="100"></a></td><td colspan=6 align=right class="TDS">user</td><tr>

	<tr class="oswmenu" height="40" align="center">
	    <td><b>№</b></td>
	    <td><b>ДАТА ПОСТУПЛЕНИЯ</b></td>
	    <td><b>ДОГОВОР №</b></td>
	    <td><b>ПРИЧИНА</b></td>
	    <td><b>К.ТЕЛЕФОН</b></td>
	    <td><b>ПОСЕЛОК</b></td>
	    <td><b>КОМЕНТАРИЙ ОТ АБОНЕНТА</b></td>
	    <td><b>СТАТУС</b></td>
	    <td><b>ДАТА РЕМОНТА</b></td>
	    <td><b>КОМЕНТАРИЙ ОТ МОНТАЖНИКОВ</b></td>
	    <td><b>ОЖИДАНИЕ</b></td>
	    <td><b>EDIT</b></td>
	</tr>



	<tr class="osw" align="center">
	    <td>1</td>
	    <td>07.07.22</td>
	    <td>07.07.22</td>
	    <td>07.07.22</td>
	    <td>07.07.22</td>
	    <td>07.07.22</td>
	    <td>07.07.22</td>
	    <td>07.07.22</td>
	    <td>07.07.22</td>
	    <td>07.07.22</td>
	    <td>07.07.22</td>
	    <td>edit</td>
	</tr>



    </table>






 </body>
</html>

work/templates/claim/claim_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <a class="brand" href="{% url 'console_repair:index' %}" title="КАТ-ТЕЛЕКОМ" aria-label="КАТ-ТЕЛЕКОМ"><img src="{% static 'img/logo_kat.png' %}" alt="" width="100"></a>
</head>
<body>
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">
        Сохранить
    </button>
</body>
</html>

work/templates/claim/claim_update.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <a class="brand" href="{% url 'console_repair:index' %}" title="КАТ-ТЕЛЕКОМ" aria-label="КАТ-ТЕЛЕКОМ"><img src="{% static 'img/logo_kat.png' %}" alt="" width="100"></a>
</head>
<body>
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">
        Редактировать
    </button>
</body>
</html>