work/claim/urls.py
from django.urls import path

from . import views

app_name = 'claim'

urlpatterns = [
    path('all/', views.claim_all, name='claim_all'),
    # path('detail/<int:claim_id>/', name='claim_detail'),
    path('create/', views.claim_create, name='claim_create'),
    path('update/<claim_id>/edit', views.claim_edit, name='claim_update')
]

work/console_repair/urls.py
from django.urls import path

from . import views

app_name = 'console_repair'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.console_repair_create, name='console_create'),
    path('console_repair/<int:repair_id>/',
         views.console_repair_detail, name='console_detail'),
    path('console_repair_all/', views.console_repair_all, name='console_all')
]

work/work/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',
         include(
             'console_repair.urls',
             namespace='console_repair')
         ),
    path('claim/',
         include
         ('claim.urls',
          namespace='claim')),
    path('admin/', admin.site.urls),
]

work/console_repair/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()


class RepairBodyState(models.TextChoices):
    DAMAGED = 'D', 'Поврежден'
    SCRATCHED = 'S', 'Потертости'
    INTACT = 'I', 'Без повреждений'


class ChoicesTypeOfConsole(models.TextChoices):
    NTE_RG_1402_F = '1', 'NTE-RG-1402F'
    NTE_RG_1402_G = '2', 'NTE-RG-1402G'
    NTE_RG_1400_F = '3', 'NTE-RG-1400F'
    NTE_RG_1400_G = '4', 'NTE-RG-1400G'
    NTE_RG_1400 = '5', 'NTE-RG-1400'
    NTE_2 = '6', 'NTE-2'


class Console(models.Model):
    type = models.CharField(
        'Тип приставки абонента',
        choices=ChoicesTypeOfConsole.choices,
        max_length=2)
    serial_number = models.CharField(
        'Серийный номер №',
        max_length=50)
    pub_date = models.DateField(
        "Дата прихода",
        default=timezone.now
    )

    class Meta:
        ordering = ("-pub_date",)
        constraints = (
            models.CheckConstraint(
                name='valid_console_choice',
                check=models.Q(type__in=ChoicesTypeOfConsole.values)
            ),
        )

    def get_type(self):
        return ChoicesTypeOfConsole(self.type)

    def __str__(self):
        return f'{self.get_type().label} - {self.serial_number}'


class Repair(models.Model):
    CHOICES_FIXING = (
        (True, 'Да'),
        (False, 'Нет'),
    )
    CHOICES_PORTS_WAN = (
        (True, 'Исправны'),
        (False, 'Не исправны'),
        (None, 'Невозможно проверить'),
    )
    CHOICES_STICKERS = (
        (True, 'Без повреждений'),
        (False, 'Отсутсвуют'),
    )

    statement = models.CharField("Дефектная ведомость", max_length=10)
    number_of_contract = models.CharField("Номер договора", max_length=10)
    name = models.CharField('ФИО', max_length=150)
    fixing = models.BooleanField(
        'Крепежные элементы в порядке',
        choices=CHOICES_FIXING,
    )
    ports_wan = models.BooleanField(
        'Работоспособность портов',
        choices=CHOICES_PORTS_WAN,
        blank=True,
        null=True,
    )
    stickers = models.BooleanField(
        'Заводские наклейки/пломбы',
        choices=CHOICES_STICKERS,
    )
    body = models.CharField(
        'Целостность корпуса',
        choices=RepairBodyState.choices,
        max_length=1)
    description = models.TextField(
        'Заключение о состоянии оборудования',
        max_length=200)
    pub_date = models.DateTimeField(
        "Дата сдачи в ремонт",
        auto_now_add=True,
    )
    console = models.ForeignKey(
        Console,
        on_delete=models.SET_NULL,
        null=True,
        blank=True)

    change_console = models.ForeignKey(
        Console,
        related_name='change_repair',
        on_delete=models.SET_NULL,
        null=True,
        blank=True)

    class Meta:
        ordering = ("-pub_date",)
        constraints = (
            models.CheckConstraint(
                name='valid_body_state_choice',
                check=models.Q(body__in=RepairBodyState.values)
            ),
        )
        verbose_name = "Дефектные ведомости"
        verbose_name_plural = "Дефектные ведомости"

    def __str__(self):
        return self.name

    def get_body(self):
        return RepairBodyState(self.body)

work/console_repair/forms.py
from django.forms import ModelForm

from .models import Repair, Console, ChoicesTypeOfConsole
from django import forms


class ConsoleForm(ModelForm):
    class Meta:
        model = Console
        fields = '__all__'
        widgets = {
            'pub_date': forms.DateInput(attrs={'type': 'date'})
        }


class RepairForm(ModelForm):
    console_type = forms.ChoiceField(label='Тип приставки абонента', choices=ChoicesTypeOfConsole.choices)
    serial_number = forms.CharField(label='Серийный номер №', max_length=50)
    change_console_type = forms.ChoiceField(label='Тип подменной приставки', choices=ChoicesTypeOfConsole.choices)
    serial_number_change = forms.CharField(label='Серийный номер №', max_length=50)

    class Meta:
        model = Repair
        fields = (
            'statement',
            'number_of_contract',
            'name',
            'fixing',
            'ports_wan',
            'stickers',
            'body',
            'console_type',
            'serial_number',
            'change_console_type',
            'serial_number_change',
            'description',

        )

    def save(self, commit=True):
        console_type = self.cleaned_data.pop('console_type')
        serial_number = self.cleaned_data.pop('serial_number')
        change_console_type = self.cleaned_data.pop('change_console_type')
        serial_number_change = self.cleaned_data.pop('serial_number_change')

        repair = super().save(commit=False)
        console, _ = Console.objects.get_or_create(type=console_type, serial_number=serial_number)
        change_console, _ = Console.objects.get_or_create(type=change_console_type, serial_number=serial_number_change)
        repair.console = console
        repair.change_console = change_console

        if commit:
            repair.save()

        return repair

work/console_repair/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .forms import RepairForm
from .models import Repair


def index(request):
    repair = Repair.objects.all()
    context = {
        'console': repair
    }
    return render(request, 'console_repair/index.html', context)


def console_repair_all(request):
    repair = Repair.objects.all()
    context = {
        'repairs': repair,
    }
    return render(request, 'console_repair/console_repair_all.html', context)


def console_repair_detail(request, repair_id):
    console = get_object_or_404(Repair, id=repair_id)
    context = {
        'repair': console,
    }
    return render(
        request,
        'console_repair/console_repair_detail.html',
        context)


def console_repair_create(request):
    form = RepairForm(request.POST)
    if form.is_valid():
        repair = form.save()
        return redirect('console_repair:detail', repair_id=repair.id)
    context = {
        'form': form,
    }
    return render(request, 'console_repair/console_repair_form.html', context)

work/templates/console_repair/console_all.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Все приставки</title>
    <style type="text/css">
    .f14px {
    font-size: 20px;
    }
    .f8px {
    font-size: 14px;
    }

    .table1 {
     border: 1px #ff0000 solid; /* стиль рамки */
     border-collapse: collapse ; /* убирание задвоенности рамки */
     text-align: center;
     vertical-align: middle;
    }
  </style>
    <a class="brand" href="{% url 'console_repair:index' %}" title="КАТ-ТЕЛЕКОМ" aria-label="КАТ-ТЕЛЕКОМ"><img src="{% static 'img/logo_kat.png' %}" alt="" width="100"></a>
</head>
<body>
<table width=100% border=1 class=table1>
    <thead>
    <tr>
        <th>Дата прихода</th>
        <th>Тип приставки</th>
        <th>Серийный номер</th>
        <th>Дата настройки</th>
    </tr>
    </thead>
    <tbody>
    {% for repair in repairs %}
    <tr>
        <td>{{ repair.pub_date }}</td>
        <td>{{ repair.statement }}</td>
        <td>{{ repair.number_of_contract }}</td>
        <td>{{ repair.name }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

work/templates/console_repair/console_repair_all.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Все ведомости</title>
    <style type="text/css">
    .f14px {
    font-size: 20px;
    }
    .f8px {
    font-size: 14px;
    }

    .table1 {
     border: 1px #ff0000 solid; /* стиль рамки */
     border-collapse: collapse ; /* убирание задвоенности рамки */
     text-align: center;
     vertical-align: middle;
    }
  </style>
    <a class="brand" href="{% url 'console_repair:index' %}" title="КАТ-ТЕЛЕКОМ" aria-label="КАТ-ТЕЛЕКОМ"><img src="{% static 'img/logo_kat.png' %}" alt="" width="100"></a>
</head>
<body>
<table width=100% border=1 class=table1>
    <thead>
    <tr>
        <th>Дата ведомости</th>
        <th>Дефектная ведомость №</th>
        <th>Номер договора</th>
        <th>ФИО</th>
        <th>Подробности</th>
    </tr>
    </thead>
    <tbody>
    {% for repair in repairs %}
    <tr>
        <td>{{ repair.pub_date }}</td>
        <td>{{ repair.statement }}</td>
        <td>{{ repair.number_of_contract }}</td>
        <td>{{ repair.name }}</td>
        <td><a href="{% url 'console_repair:console_detail' repair.id %}">Подробнее</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

work/templates/console_repair/console_repair_detail.html
<!DOCTYPE html >
<html lang="ru">
 <head>
  <meta charset=utf-8" />
  <title>Подробности</title>
  <style type="text/css">
    .f14px {
    font-size: 20px;
    }
    .f8px {
    font-size: 14px;
    }

    .table1 {
     border: 1px #ff0000 solid; /* стиль рамки */
     border-collapse: collapse ; /* убирание задвоенности рамки */
     text-align: center;
     vertical-align: middle;
    }
  </style>
<style type="text/css" media="print">
@page {
    size: auto;
    margin: 0;
}
</style>
 </head>
 <body>

<div align=center class=f14px><b>ДЕФЕКТНАЯ ВЕДОМОСТЬ №  от {{ repair.statement }}</b></div>
<br>
Номер договора: {{ repair.number_of_contract }}  /  Ф.И.О: {{ repair.name }}  <br>
Оборудование: {{ repair.console.get_type.label }} , Серийный номер: {{ repair.console.serial_number}} <br>
<br>

<b>Описание внешнего вида оборудования:</b><br>
1.Внешние повреждения: потертости (значительные/незначительные): ___________________________<br>
2.Крепежные элементы в порядке:{{ repair.fixing|yesno:"Да,Нет" }} <br>
3.Работоспособность портов: {{ repair.ports_wan|yesno:"Исправны,Не исправны,Невозможно проверить" }} <br>
4.Заводские наклейки/пломбы: {{ repair.stickers|yesno:"Без повреждений,Отсутсвуют" }}<br>
5.Целостность корпуса/корпус поврежден/ не поврежден: {{ repair.get_body.label }} <br><br>
<table width=100% border=1 class=table1>
  <tr>
   <td width=100>Дата</td>
   <td>Наименование оборудования<br>(серийный номер, модель)</td>
   <td>Оборудование</td>
   <td>Заключение о состоянии оборудования</td>
  </tr>
  <tr>
   <td>{{ repair.pub_date|date:"d E Y" }}</td>
   <td>Комплектность: {{ repair.console.get_type.label }}<br><br>SN:{{ repair.console.serial_number }}</td>
   <td>Сдача в ремонт</td>
   <td>{{ repair.description }}</td>
  </tr>
  <tr>
   <td>{{ repair.pub_date|date:"d E Y" }}</td>
   <td>Комплектность: {{ repair.change_console.get_type.label }}<br><br>SN:{{ repair.change_console.serial_number }} </td>
   <td>Выдача подменного оборудования</td>
   <td><br><br></td></tr>
  <tr>
   <td> </td><td>Комплектность</td><td>Выдача из ремонта</td>
   <td><br><br></td>
  </tr>
  <tr>
   <td> </td>
   <td>Комплектность</td>
   <td>Возврат подменного оборудования</td>
   <td><br><br></td>
  </tr>
</table>
<br>
<div class="f8px">
<div align=center><b>Условия приема-сдачи оборудования в ремонт</b></div>
<br>
1.  Прием-сдача оборудования осуществляется только собственником договора с наличием документа удостоверяющего личность.
<br>
2.  На момент сдачи неисправного оборудования в ремонт по гарантии, по личному заявлению владельца договора выдается подменное оборудование при его наличии на период нахождения неисправного оборудования в ремонте.
<br>
&nbsp;&nbsp;&nbsp;&nbsp;В случае если в процессе диагностики оборудования будет выявлено, что оборудование пришло в негодность по вине собственника, это не будет являться гарантийным случаем.
<b>Ремонт оплачивается собственником оборудования в течении 14 календарных дней с момента оповещения о поступлении оборудования с ремонта*.</b>
<br>    В случае если, в процессе диагностики оборудование будет признано неремонтопригодным по вине собственника, тогда оборудование возвращается собственнику. При этом собственник должен вернуть подменное оборудование или выкупить его**.
<br>
3.  На момент сдачи неисправного оборудования в ремонт не по гарантии, по личному заявлению владельца договора выдается подменное оборудование при его наличии на период нахождения неисправного оборудования в ремонте.
<br>&nbsp;&nbsp;&nbsp;&nbsp;<b>Не гарантийный ремонт оплачивается собственником оборудования. Собственник обязуется забрать оборудование, пришедшее из ремонта, оплатить ремонт оборудования и вернуть подменное оборудование в течении 14 календарных дней с момента оповещения о поступлении оборудования с ремонта*.
</b>
<br>&nbsp;&nbsp;&nbsp;&nbsp;В случае если в процессе диагностики оборудование будет признано неремонтопригодным, тогда оборудование возвращается собственнику. При этом собственник должен вернуть подменное оборудование или выкупить его**.
</div>
<br>
<div align=right>С условиями приема и сдачи оборудования ознакомлен и согласен</div>
<br>
<table width=100%>
<tr>
<td>
Генеральный директор<br>
ООО «КАТ-Телеком»<br><br>
__________________/А.С. Аржаев <br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;М.П.
</td>
<td>
Собственник договора<br>
______________ /___________ <br>
</td>
</tr>
</table>
<br>
<div class="f8px">
* Стоимость ремонта зависит от неисправности и составляет сумму от 800 до 2000 рублей.<br>
**Стоимость зависит от модели оборудования находящегося на подмене (от 2000 до 4000 рублей)
</div>

</body>

work/templates/console_repair/console_repair_form.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Создание ведомости</title>
    <a class="brand" href="{% url 'console_repair:index' %}" title="КАТ-ТЕЛЕКОМ" aria-label="КАТ-ТЕЛЕКОМ"><img src="{% static 'img/logo_kat.png' %}" alt="" width="100"></a>
</head>
<body>
<form method="POST" class="post-form">
    {% csrf_token %}
<!--    {{ form.as_p }}-->

    {% for field in form %}
    <div class="fieldWrapper {{ field.name }}">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}




    <button type="submit" class="btn btn-primary">
        Сохранить
    </button>
</body>
</html>

work/templates/console_repair/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
    <a class="brand" href="{% url 'console_repair:index' %}" title="КАТ-ТЕЛЕКОМ" aria-label="КАТ-ТЕЛЕКОМ"><img src="{% static 'img/logo_kat.png' %}" alt="" width="100"></a>
</head>
<body>
<h1>Дефектные ведомости</h1>
<p><a href="{% url 'console_repair:console_create' %}">Создать новую дефектную ведомость</a></p>
<p><a href="{% url 'console_repair:console_all' %}">Все дефектные ведомости</a></p>
<h1>Заказ наряд</h1>
<p><a href="{% url 'claim:claim_create' %}">Создать новый заказ наряд</a></p>
<p><a href="{% url 'claim:claim_all' %}">Все заказ наряды</a></p>

</body>
</html>

work/templates/console_repair/new_console.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>